version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: "mongo"
    volumes: 
      - data:/data/db
    env_file:
      - ./mongo.env
    # networks:
    #   - goals-net

  backend:
    container_name: backend
    build: "./backend"
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    #     args:
    #       key: value
    ports:
      - "80:80"
    volumes: 
      - logs:/app/logs
      - ./backend:/app
      - app/node_modules
    env_file:
      - ./node.env
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    build: "./frontend"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: